name: ci

on:
    push:
        paths:
            - "prueba3/index.html"

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to DockeHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v3
              with:
                file: prueba3/Dockerfile
                context: prueba3
                push: true
                tags: vanloic/craftech:${{ github.sha }}